# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'linish_react_native' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for linish_react_native
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTText',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]

  target 'linish_react_nativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
