# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'linish_ios' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for linish_ios
  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON'
  pod 'JSQMessagesViewController'

  target 'linish_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'linish_iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
